### ISSUE TITLE
Any plans on releasing the source code?

### ISSUE THREAD

**Issue by Phara0h** [stoyannk/voxels#1]
I was wondering if you had any plans of actually releasing the source code or you were just going to keep it closed source forever.

**Comment by stoyannk** [comment]
I plan to release it, but before that I'd like to do some clean-up. Unfortunately my day-to-day work leaves me very little time to dedicate to the library.

**Comment by Phara0h** [comment]
no need to clean it up mate! that's why you open it up to open source so other people can help you do that! :)

**Comment by Phara0h** [comment]
Any chances on this happening?

**Comment by stoyannk** [comment]
I can't commit to do this soon. I'm very busy with my company and unfortunately releasing the code for the library is low on my priority list. I'd like to dedicate time to voxels, but I really can't at the moment.
